import Image from "next/image";
import { Reveal } from "@/components/motion/Reveal";
import { Parallax } from "@/components/motion/Parallax";
import { Concentric, Checker } from "@/components/decor/Stickers";
import { NumberSpecimen } from "@/components/decor/Specimens";

type Part = {
  src: string;
  alt: string;
  prompt: string;
  color: string;
  span: string;
  aspect: string;
};

const PARTS: Part[] = [
  { src: "/parts/valve-housing.png", alt: "A three-port valve housing with a threaded bore, generated by Archie from its STEP output.", prompt: "a three-port valve housing", color: "sky", span: "sm:col-span-2 lg:col-span-8", aspect: "aspect-[16/10]" },
  { src: "/parts/gearbox-housing.png", alt: "A ribbed gearbox housing with an oval mounting flange, generated by Archie.", prompt: "a ribbed gearbox housing", color: "coral", span: "lg:col-span-4", aspect: "aspect-[16/10] lg:aspect-auto" },
  { src: "/parts/bell-housing.png", alt: "A bell housing with bolt bosses and gusseted webs, generated by Archie.", prompt: "a bell housing, gussets", color: "lime", span: "lg:col-span-4", aspect: "aspect-[4/3]" },
  { src: "/parts/sensor-mount.png", alt: "A sensor mount with two mounting tabs and an inset circular pocket, generated by Archie.", prompt: "a sensor mount, inset pocket", color: "peri", span: "lg:col-span-4", aspect: "aspect-[4/3]" },
  { src: "/parts/volute-plate.png", alt: "A pump volute backplate with a central boss, generated by Archie.", prompt: "a pump volute backplate", color: "gold", span: "lg:col-span-4", aspect: "aspect-[4/3]" },
  { src: "/parts/intake-gasket.png", alt: "A four-runner intake gasket, generated by Archie.", prompt: "a four-runner intake gasket", color: "olive", span: "sm:col-span-2 lg:col-span-12", aspect: "aspect-[24/6]" },
];

function PartTile({ part }: { part: Part }) {
  return (
    <figure
      className={`part-tile relative overflow-hidden ${part.span} ${part.aspect}`}
      style={{ backgroundColor: `color-mix(in srgb, var(--color-${part.color}) 40%, var(--color-cream))` }}
    >
      <Image src={part.src} alt={part.alt} fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-contain p-3 md:p-4" />
      <figcaption className="absolute inset-x-0 bottom-0 flex items-center justify-between gap-2 border-t-[2.5px] border-ink bg-cream px-3 py-1.5">
        <code className="u-mono text-[11.5px] text-ink">
          <span className="text-ink-mute">you:</span> {part.prompt}
        </code>
        <span className="font-mono text-[9.5px] font-bold uppercase tracking-[0.12em] text-ink-mute">archie · built</span>
      </figcaption>
    </figure>
  );
}

export function AnyoneCanBuild() {
  return (
    <section id="output" className="relative scroll-mt-24 overflow-hidden bg-cream py-24 md:py-32">
      <Parallax y={40} className="pointer-events-none absolute -left-14 bottom-24 hidden md:block">
        <Concentric className="h-40 w-40 text-coral" />
      </Parallax>
      <Checker n={4} className="pointer-events-none absolute right-8 top-16 hidden h-16 w-16 lg:block" aria-hidden />
      <NumberSpecimen n="6" className="pointer-events-none absolute right-[6%] bottom-16 hidden select-none text-[7rem] leading-none text-olive/30 lg:block" />

      <div className="relative mx-auto w-full max-w-[1400px] px-4 md:px-8">
        <div className="max-w-3xl">
          <Reveal>
            <span className="inline-flex items-center border-[2.5px] border-ink bg-coral px-3 py-1.5 font-mono text-[11px] font-bold uppercase tracking-[0.16em] text-ink">
              Real output · not renders
            </span>
          </Reveal>
          <Reveal delay={0.06}>
            <h2 className="mt-6 font-display text-h1 text-ink">
              If you can describe it, you can{" "}
              <span className="inline-block -rotate-1 border-[3px] border-ink bg-lime px-2 leading-[1.1]">build it.</span>
            </h2>
          </Reveal>
          <Reveal delay={0.12}>
            <p className="mt-6 max-w-[44ch] text-lead text-ink-soft">Each from a single line. Rendered from real STEP.</p>
          </Reveal>
        </div>

        {/* butted color-field grid — ink seams via gap on an ink ground */}
        <Reveal delay={0.08}>
          <div className="mt-12 grid grid-cols-1 gap-[2.5px] border-[2.5px] border-ink bg-ink sm:grid-cols-2 lg:grid-cols-12">
            {PARTS.map((p) => (
              <PartTile key={p.src} part={p} />
            ))}
          </div>
        </Reveal>
      </div>
    </section>
  );
}
