import Image from "next/image";
import { Reveal } from "@/components/motion/Reveal";
import { DieDots, Sparkle } from "@/components/decor/Stickers";

type Part = {
  src: string;
  alt: string;
  prompt: string;
  color: string; // palette token name for tag + shadow
  span: string;
  aspect: string;
  rotate: string;
};

const PARTS: Part[] = [
  { src: "/parts/valve-housing.png", alt: "A three-port valve housing with a threaded bore, generated by Archie from its STEP output.", prompt: "a three-port valve housing with a threaded bore", color: "peri", span: "lg:col-span-8", aspect: "aspect-[16/10]", rotate: "-rotate-1" },
  { src: "/parts/gearbox-housing.png", alt: "A ribbed gearbox housing with an oval mounting flange, generated by Archie.", prompt: "a ribbed gearbox housing, oval flange", color: "olive", span: "lg:col-span-4", aspect: "aspect-[16/10]", rotate: "rotate-1" },
  { src: "/parts/bell-housing.png", alt: "A bell housing with bolt bosses and gusseted webs, generated by Archie.", prompt: "a bell housing with bolt bosses and gussets", color: "coral", span: "lg:col-span-4", aspect: "aspect-[4/3]", rotate: "rotate-1" },
  { src: "/parts/sensor-mount.png", alt: "A sensor mount with two mounting tabs and an inset circular pocket, generated by Archie.", prompt: "a sensor mount, two tabs, inset pocket", color: "lav", span: "lg:col-span-4", aspect: "aspect-[4/3]", rotate: "-rotate-1" },
  { src: "/parts/volute-plate.png", alt: "A pump volute backplate with a central boss, generated by Archie.", prompt: "a pump volute backplate", color: "lime", span: "lg:col-span-4", aspect: "aspect-[4/3]", rotate: "rotate-1" },
  { src: "/parts/intake-gasket.png", alt: "A four-runner intake gasket, generated by Archie.", prompt: "a four-runner intake gasket", color: "sky", span: "lg:col-span-12", aspect: "aspect-[24/6]", rotate: "-rotate-1" },
];

function PartTile({ part }: { part: Part }) {
  return (
    <figure
      className={`part-tile group relative overflow-hidden rounded-xl border-[2.5px] border-ink bg-cream-2 ${part.span} ${part.aspect} ${part.rotate} transition-transform duration-200 hover:rotate-0`}
      style={{ boxShadow: `8px 8px 0 0 var(--color-${part.color})` }}
    >
      <span
        className="absolute left-3 top-3 z-10 rounded-md border-2 border-ink px-2 py-0.5 font-mono text-[9.5px] font-bold uppercase tracking-[0.12em] text-ink"
        style={{ backgroundColor: `var(--color-${part.color})` }}
      >
        Archie · built
      </span>
      <Image
        src={part.src}
        alt={part.alt}
        fill
        sizes="(max-width: 1024px) 100vw, 55vw"
        className="object-contain p-5 md:p-6"
      />
      <figcaption className="absolute inset-x-0 bottom-0 border-t-2 border-ink bg-cream px-4 py-2">
        <code className="u-mono text-[12px] text-ink">
          <span className="text-ink-mute">you:</span> {part.prompt}
        </code>
      </figcaption>
    </figure>
  );
}

export function AnyoneCanBuild() {
  return (
    <section id="output" className="relative scroll-mt-24 overflow-hidden py-24 md:py-32">
      <div className="mx-auto w-full max-w-[1400px] px-4 md:px-8">
        <div className="relative max-w-3xl">
          <Sparkle className="absolute -left-2 -top-10 hidden h-12 w-12 text-lime md:block" aria-hidden />
          <Reveal>
            <span className="eyebrow bg-coral text-cream">Real output · not renders</span>
          </Reveal>
          <Reveal delay={0.06}>
            <h2 className="mt-6 font-display text-h1 text-ink">
              If you can describe it, you can{" "}
              <span className="inline-block -rotate-1 rounded-lg border-[3px] border-ink bg-lime px-2 nb-shadow-sm">
                build it.
              </span>
            </h2>
          </Reveal>
          <Reveal delay={0.12}>
            <p className="mt-6 max-w-[44ch] text-lead text-ink-soft">
              Each from a single line. Rendered from real STEP.
            </p>
          </Reveal>
        </div>

        <Reveal delay={0.08}>
          <div className="mt-14 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-12 lg:gap-7">
            {PARTS.map((p) => (
              <PartTile key={p.src} part={p} />
            ))}
          </div>
        </Reveal>

        <DieDots className="mx-auto mt-14 h-10 w-10 text-olive" aria-hidden />
      </div>
    </section>
  );
}
